#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

# ------------------------------------------------------------------ #
# Example 1-5: Selecting a site with --root and --uri
# ------------------------------------------------------------------ #

drush --root=$DIR/dgd7/web --uri=dgd7.org core-status "Site URI"

# ------------------------------------------------------------------ #
