#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

# ------------------------------------------------------------------ #
# Example 1-3: Drush core-status, site selected via `cd`
# ------------------------------------------------------------------ #

cd dgd7/web/sites/default/
drush core-status

# ------------------------------------------------------------------ #
