#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

# ------------------------------------------------------------------ #
# Example 2-3: Show release notes
# ------------------------------------------------------------------ #

drush @dev pm-releasenotes logintoboggan --pipe
drush @dev pm-releasenotes webform --pipe

# ------------------------------------------------------------------ #
