#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

# ------------------------------------------------------------------ #
# Example 2-3: Lock the logintoboggan module
# ------------------------------------------------------------------ #

drush @dev pm-updatecode --lock=logintoboggan

# ------------------------------------------------------------------ #
