#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

drush @dev pm-enable logintoboggan
drush @dev pm-updatecode --unlock=all -y 

# ------------------------------------------------------------------ #
# Example 2-5: Updatedb
# ------------------------------------------------------------------ #

drush @dev updatedb

# ------------------------------------------------------------------ #
