#!/bin/bash
self=$0
bin=${self%/*}
. $bin/00-00-init
set -o verbose

# ------------------------------------------------------------------ #
# Example 5-3: drush sql-sync
# ------------------------------------------------------------------ #

drush sql-sync @live @dev --create-db -s
drush sql-sync @live @dev --create-db -y

# ------------------------------------------------------------------ #
